#include <string.h>

#include "instruction.h"
#include "utils.h"

static const instruction_desc instruction_table[] =
{
	{"ADD", R3, FUNCT_ADD, ADD},
	{"ADDI", R3_IMMEDIATE, OPCODE_ADDI, ADDI},
	{"ADDIU", R3_IMMEDIATE, OPCODE_ADDIU, ADDIU},
	{"ADDU", R3, FUNCT_ADDU, ADDU},
	{"AND", R3, FUNCT_AND, AND},
	{"ANDI", R3_IMMEDIATE, OPCODE_ANDI, ANDI},
	{"AUI", R3_IMMEDIATE, OPCODE_AUI, AUI},
	{"BEQ", BRANCH_R2, OPCODE_BEQ, BEQ},
	{"BGEZ", BRANCH_R1, OPCODE_REGIMM, BGEZ},
	{"BGTZ", BRANCH_R1, OPCODE_BGTZ, BGTZ},
	{"BLEZ", BRANCH_R1, OPCODE_BLEZ, BLEZ},
	{"BLTZ", BRANCH_R1, OPCODE_REGIMM, BLTZ},
	{"BNE", BRANCH_R2, OPCODE_BNE, BNE},
	{"CLO", RD_RS, FUNCT_CLO, CLO}, 
	{"CLZ", RD_RS, FUNCT_CLZ, CLZ},
	{"DIV", R2, FUNCT_DIV, DIV},
	{"EXIT", CMD_EXIT, 0, 0},
	{"J", TARGET, OPCODE_J, J},
	{"JAL", TARGET, OPCODE_JAL, JAL},
	{"JR", RS, FUNCT_JR, JR},
	{"LB", MEMORY, OPCODE_LB, LB},
	{"LBU", MEMORY, OPCODE_LBU, LBU},
	{"LH", MEMORY, OPCODE_LH, LH},
	{"LHU", MEMORY, OPCODE_LHU, LHU},
	{"LUI", RT_IMMEDIATE, OPCODE_AUI, AUI},
	{"LW", MEMORY, OPCODE_LW, LW},
	{"MFHI", RD, FUNCT_MFHI, MFHI},
	{"MFLO", RD, FUNCT_MFLO, MFLO},
	{"MTHI", RS, FUNCT_MTHI, MTHI},
	{"MTLO", RS, FUNCT_MTLO, MTLO},
	{"MULT", R2, FUNCT_MULT, MULT},
	{"NOP", CMD_NOP, 0, NOP},
	{"NOR", R3, FUNCT_NOR, NOR},
	{"OR", R3, FUNCT_OR, OR},
	{"ORI", R3_IMMEDIATE, OPCODE_ORI, ORI},
	{"ROTR", SHIFT, FUNCT_SRL, ROTR},
	{"ROTRV", VARIABLE_SHIFT, FUNCT_SRLV, ROTRV},
	{"SB", MEMORY, OPCODE_SB, SB},
	{"SELEQZ", R3, FUNCT_SELEQZ, SELEQZ},
	{"SELNEZ", R3, FUNCT_SELNEZ, SELNEZ},
	{"SH", MEMORY, OPCODE_SH, SH},
	{"SLL", SHIFT, FUNCT_SLL, SLL},
	{"SLLV", VARIABLE_SHIFT, FUNCT_SLLV, SLLV},
	{"SLT", R3, FUNCT_SLT, SLT},
	{"SLTI", R3_IMMEDIATE, OPCODE_SLTI, SLTI},
	{"SLTIU", R3_IMMEDIATE, OPCODE_SLTIU, SLTIU},
	{"SLTU", R3, FUNCT_SLTU, SLTU},
	{"SRA", SHIFT, FUNCT_SRA, SRA},
	{"SRAV", VARIABLE_SHIFT, FUNCT_SRAV, SRAV},
	{"SRL", SHIFT, FUNCT_SRL, SRL},
	{"SRLV", VARIABLE_SHIFT, FUNCT_SRLV, SRLV},
	{"SUB", R3, FUNCT_SUB, SUB},
	{"SUBU", R3, FUNCT_SUBU, SUBU},
	{"SW", MEMORY, OPCODE_SW, SW},
	{"XOR", R3, FUNCT_XOR, XOR},
	{"XORI", R3_IMMEDIATE, OPCODE_XORI, XORI}
};

const instruction_desc *find_instruction(const char *mnemonic)
{
	for(size_t i = 0; i < ARR_SIZE(instruction_table); i++)
		if(!strcmp(mnemonic, instruction_table[i].mnemonic)) return(&instruction_table[i]);
	return(NULL);
}